#!/usr/bin/env python3
"""Regenerates src/embedded_assets.h from the Kenney Input Prompts pack.

Converts a fixed list of "Xbox Series/Default/*.png" icons (already 64x64,
true per-pixel alpha) out of kenney_input-prompts_1.5.zip at the repo root
into the same 32bpp BI_RGB .bmp-in-a-byte-array format
mad2inputdisplay/src/inputdisplay.cpp's CreateTextureFromBmp already parses:
bottom-up row order, B,G,R,A byte order per pixel (which is BMP's native
in-memory layout, and happens to equal D3DFMT_A8R8G8B8's on a little-endian
target -- see that function's header comment).

Usage: python3 gen_embedded_assets.py
(no arguments; paths are relative to this script's location)
"""
import io
import os
import struct
import zipfile

from PIL import Image

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
ZIP_PATH = os.path.join(REPO_ROOT, "kenney_input-prompts_1.5.zip")
ASSETS_DIR = os.path.join(SCRIPT_DIR, "..", "assets")
OUTPUT_PATH = os.path.join(SCRIPT_DIR, "..", "src", "embedded_assets.h")

# (const-name, source .bmp/.png basename for assets/, zip-relative path).
# The first 7 are the mod's original fixed icon set (kept, unchanged
# const names, so inputdisplay.cpp's existing texture loads don't need to
# change); the rest are the expanded set added for per-icon config toggles.
ICONS = [
    ("Dpad", "xbox_dpad.png", "Xbox Series/Default/xbox_dpad.png"),
    ("Start", "xbox_button_start.png", "Xbox Series/Default/xbox_button_start.png"),
    ("A", "xbox_button_color_a.png", "Xbox Series/Default/xbox_button_color_a.png"),
    ("B", "xbox_button_color_b.png", "Xbox Series/Default/xbox_button_color_b.png"),
    ("X", "xbox_button_color_x.png", "Xbox Series/Default/xbox_button_color_x.png"),
    ("Y", "xbox_button_color_y.png", "Xbox Series/Default/xbox_button_color_y.png"),
    ("Lb", "xbox_lb.png", "Xbox Series/Default/xbox_lb.png"),
    ("Rb", "xbox_rb.png", "Xbox Series/Default/xbox_rb.png"),
    ("Lt", "xbox_lt.png", "Xbox Series/Default/xbox_lt.png"),
    ("Rt", "xbox_rt.png", "Xbox Series/Default/xbox_rt.png"),
    ("Back", "xbox_button_back.png", "Xbox Series/Default/xbox_button_back.png"),
    ("Ls", "xbox_ls.png", "Xbox Series/Default/xbox_ls.png"),
    ("Rs", "xbox_rs.png", "Xbox Series/Default/xbox_rs.png"),
]
# Note: "View" and "Guide" icons exist in the Kenney pack but are
# deliberately not included here. XINPUT_GAMEPAD has no bit for either --
# Series controllers' "View" button reports through the same legacy
# XINPUT_GAMEPAD_BACK bit as "Back" (so a separate toggle would just be a
# duplicate of ShowBack with different art), and the Guide/Xbox button is
# reserved by the OS and never reported through XInputGetState at all, so
# there'd be no way to ever light up a "pressed" state for it.


def png_to_bmp_bytes(png_bytes: bytes) -> bytes:
    img = Image.open(io.BytesIO(png_bytes)).convert("RGBA")
    width, height = img.size
    row_bytes = width * 4
    pixel_data = bytearray(row_bytes * height)
    src = img.tobytes()  # R,G,B,A per pixel, top-down rows
    for y in range(height):
        dst_row = height - 1 - y  # BMP rows are bottom-up
        for x in range(width):
            si = (y * width + x) * 4
            r, g, b, a = src[si], src[si + 1], src[si + 2], src[si + 3]
            di = dst_row * row_bytes + x * 4
            pixel_data[di] = b
            pixel_data[di + 1] = g
            pixel_data[di + 2] = r
            pixel_data[di + 3] = a

    data_offset = 54
    file_size = data_offset + len(pixel_data)
    file_header = struct.pack("<2sIHHI", b"BM", file_size, 0, 0, data_offset)
    dib_header = struct.pack(
        "<IiiHHIIiiII",
        40,  # biSize
        width,
        height,
        1,  # biPlanes
        32,  # biBitCount
        0,  # biCompression (BI_RGB)
        len(pixel_data),  # biSizeImage
        3780,  # biXPelsPerMeter (matches the existing hand-generated assets)
        3780,  # biYPelsPerMeter
        0,  # biClrUsed
        0,  # biClrImportant
    )
    return file_header + dib_header + bytes(pixel_data)


def emit_array(out, const_name: str, bmp_bytes: bytes, source_name: str):
    out.write(f"// {source_name} ({len(bmp_bytes)} bytes)\n")
    out.write(f"static const uint8_t kBmp{const_name}[] = {{\n")
    for i in range(0, len(bmp_bytes), 20):
        chunk = bmp_bytes[i : i + 20]
        out.write("    " + ",".join(str(b) for b in chunk) + ",\n")
    out.write("};\n")
    out.write(f"static const size_t kBmp{const_name}Len = sizeof(kBmp{const_name});\n\n")


def main():
    os.makedirs(ASSETS_DIR, exist_ok=True)
    with zipfile.ZipFile(ZIP_PATH) as zf, open(OUTPUT_PATH, "w") as out:
        out.write("#pragma once\n")
        out.write(
            "// Generated by tools/gen_embedded_assets.py from the Kenney Input Prompts\n"
            "// pack (kenney_input-prompts_1.5.zip at the repo root, \"Xbox Series/Default\"\n"
            "// set). Embedded as compiled-in byte arrays so the mod is a single\n"
            "// self-contained DLL with no runtime asset files to ship or lose track of,\n"
            "// consistent with the rest of this repo. Do not hand-edit -- rerun the\n"
            "// script instead.\n"
        )
        out.write("#include <cstdint>\n#include <cstddef>\n\n")

        for const_name, asset_basename, zip_path in ICONS:
            png_bytes = zf.read(zip_path)
            bmp_bytes = png_to_bmp_bytes(png_bytes)

            with open(os.path.join(ASSETS_DIR, asset_basename), "wb") as f:
                f.write(png_bytes)

            emit_array(out, const_name, bmp_bytes, asset_basename)

    # Remove the old hand-generated .bmp source images -- superseded by the
    # .png files just written above (same names as the zip's originals).
    for stale in (
        "xbox_dpad.bmp",
        "xbox_button_start.bmp",
        "xbox_button_color_a.bmp",
        "xbox_button_color_b.bmp",
        "xbox_button_color_x.bmp",
        "xbox_button_color_y.bmp",
        "xbox_lb.bmp",
    ):
        stale_path = os.path.join(ASSETS_DIR, stale)
        if os.path.exists(stale_path):
            os.remove(stale_path)

    print(f"Wrote {OUTPUT_PATH}")
    print(f"Wrote {len(ICONS)} source PNGs to {ASSETS_DIR}")


if __name__ == "__main__":
    main()
