package main

import (
	"bufio"
	"bytes"
	"encoding/binary"
	"fmt"
	"os"
	"strings"

	"mad2iga"
)

// level-tree renders a whole level's object graph as an indented, human-
// readable text tree — the Go equivalent of MaxStache/madagascar-2-tools'
// myscirpt.py `level.txt` dump. It starts at Section 1's top-level object
// list and follows every ROFS pointer field and every list element (see
// mad2iga/objtree.go), resolving real names (ActorInfo._name, _varName, …)
// through the authoritative RSTR/TSTR tables. Every object is printed once;
// a re-encountered object is shown as "(already shown)" to keep the output
// finite without losing the fact that the reference exists.

// loadObjectGraph reads either a raw IGZ (level.bld) or a `.bld` igArchive
// (from which it extracts the inner level.bld) and parses its object graph.
func loadObjectGraph(path string) (*iga.ObjectGraph, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	// IGZ directly?
	if len(data) >= 4 && binary.LittleEndian.Uint32(data[:4]) == 0x49475A01 {
		return iga.ParseObjectGraph(data)
	}
	// igArchive ("IGA\x1a")? Extract the inner level.bld.
	if len(data) >= 4 && binary.LittleEndian.Uint32(data[:4]) == 0x1A414749 {
		arc, err := iga.Open(path)
		if err != nil {
			return nil, fmt.Errorf("open archive: %w", err)
		}
		defer arc.Close()
		idx := -1
		for i, e := range arc.Entries {
			if strings.EqualFold(e.Name, "level.bld") || strings.HasSuffix(strings.ToLower(e.Name), "/level.bld") {
				idx = i
				break
			}
		}
		if idx < 0 && len(arc.Entries) > 0 {
			idx = 0 // fall back to the first member, matching the reference reader
		}
		if idx < 0 {
			return nil, fmt.Errorf("archive has no members")
		}
		var buf bytes.Buffer
		if err := arc.ExtractFile(idx, &buf); err != nil {
			return nil, fmt.Errorf("extract %s: %w", arc.Entries[idx].Name, err)
		}
		return iga.ParseObjectGraph(buf.Bytes())
	}
	return nil, fmt.Errorf("%s is neither an IGZ nor an igArchive", path)
}

// nodeLabel returns a human name for an object, if one resolves.
func nodeLabel(g *iga.ObjectGraph, obj iga.ObjectRef) string {
	for _, f := range []string{"_name", "_varName"} {
		if s, ok := g.ResolveFieldName(obj, f); ok && s != "" {
			return s
		}
	}
	return ""
}

func formatScalar(v interface{}) string {
	switch t := v.(type) {
	case string:
		return fmt.Sprintf("%q", t)
	case float32:
		return fmt.Sprintf("%g", t)
	case [3]float32:
		return fmt.Sprintf("[%g, %g, %g]", t[0], t[1], t[2])
	case [16]float32:
		return fmt.Sprintf("matrix[translation=%g, %g, %g]", t[12], t[13], t[14])
	case uint32:
		return fmt.Sprintf("%d", t)
	default:
		return fmt.Sprintf("%v", t)
	}
}

func renderTreeNode(g *iga.ObjectGraph, w *bufio.Writer, obj iga.ObjectRef, depth int, seen map[uint32]bool) {
	indent := strings.Repeat("    ", depth)
	class := obj.ClassName
	if class == "" {
		class = fmt.Sprintf("<unknown:%d>", obj.ClassIdx)
	}
	label := nodeLabel(g, obj)
	labelStr := ""
	if label != "" {
		labelStr = fmt.Sprintf(" %q", label)
	}

	if seen[obj.Addr] {
		fmt.Fprintf(w, "%s%s @0x%X%s (already shown)\n", indent, class, obj.Addr, labelStr)
		return
	}
	seen[obj.Addr] = true
	fmt.Fprintf(w, "%s%s @0x%X%s\n", indent, class, obj.Addr, labelStr)

	for _, f := range g.ObjectFields(obj) {
		switch f.Kind {
		case "ptr":
			cp, _ := f.Value.(*iga.ObjectRef)
			if cp == nil {
				fmt.Fprintf(w, "%s    - %s: null\n", indent, f.Name)
				continue
			}
			fmt.Fprintf(w, "%s    - %s ->\n", indent, f.Name)
			renderTreeNode(g, w, *cp, depth+2, seen)
		default:
			fmt.Fprintf(w, "%s    - %s: %s\n", indent, f.Name, formatScalar(f.Value))
		}
	}

	for _, c := range g.ListElements(obj) {
		renderTreeNode(g, w, c.Child, depth+1, seen)
	}
}

func cmdLevelTree(path, outPath string) error {
	g, err := loadObjectGraph(path)
	if err != nil {
		return err
	}
	roots, err := g.RootObjects()
	if err != nil {
		return fmt.Errorf("read top-level objects: %w", err)
	}

	out, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("create %s: %w", outPath, err)
	}
	defer out.Close()
	w := bufio.NewWriterSize(out, 1<<20)
	defer w.Flush()

	fmt.Fprintf(w, "# %s -- object graph tree (%d sections, %d classes, %d top-level objects)\n",
		path, len(g.Sections), len(g.ClassNames), len(roots))
	fmt.Fprintf(w, "# Generated by `mad2repack level-tree`. Names (ActorInfo._name, _varName, ...)\n")
	fmt.Fprintf(w, "# resolve through the authoritative RSTR/TSTR fixup tables; pointers and list\n")
	fmt.Fprintf(w, "# elements are followed via the ROFS table. An object printed once is shown as\n")
	fmt.Fprintf(w, "# \"(already shown)\" on any later reference.\n\n")

	seen := make(map[uint32]bool)
	for _, r := range roots {
		renderTreeNode(g, w, r, 0, seen)
	}
	if err := w.Flush(); err != nil {
		return err
	}
	fmt.Printf("  wrote %s (%d top-level roots, %d objects reached)\n", outPath, len(roots), len(seen))
	return nil
}
